// Writes src/data/extrasLayout.ts from .qa/extras-layout-data.json: how the
// pictures on the printed pages after each article are presented. Nothing
// here changes a picture or its file — it says which pictures are page
// furniture rather than pictures, which tiles belong together as one sliced
// advertisement, and which small graphics must never be enlarged.
// Usage (from repo root): node .qa/extras-layout.mjs
import fs from "node:fs";

const data = JSON.parse(fs.readFileSync(".qa/extras-layout-data.json", "utf8"));
const q = (s) => JSON.stringify(s);

const lines = [];
lines.push(`/**
 * How the pictures on the printed pages after each article are presented.
 * Nothing here changes a picture or its file.
 *
 * \`hidden\` are pictures that are page furniture, not pictures: the black and
 * white masks that cut a product or a person out of its background, blank
 * panels, soft shadows and glows, gradients, ornaments, and the slivers left
 * over from an advertisement that is shown whole on the same page. Set on
 * their own they read as debris, so they are not set.
 *
 * \`composites\` are advertisements the PDF stores as a grid of tiles. Each
 * tile arrived as its own picture and was set as a scattered grid; here the
 * tiles are put back where they belong (positions in the picture's own
 * pixels), so the advertisement reads as one picture. Where a flat tile was
 * never kept, \`fills\` paints its colour; where a gap could not be filled the
 * picture is cropped to its largest complete rectangle. \`parts\` lists every
 * tile, including any the crop leaves out, so none is also set on its own.
 *
 * \`crisp\` are small graphics — QR codes, logos, set lettering — that are
 * never drawn larger than their own pixels.
 *
 * Generated by .qa/extras-layout.mjs from .qa/extras-layout-data.json — do not
 * edit by hand.
 */`);
lines.push(`export interface ExtraCompositeTile {
  src: string;
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface ExtraComposite {
  width: number;
  height: number;
  tiles: ExtraCompositeTile[];
  fills: { x: number; y: number; w: number; h: number; color: string }[];
  /** Every tile of the advertisement, including any the crop leaves out. */
  parts: string[];
}
`);
lines.push("const hidden = new Set<string>([");
let why = null;
for (const h of data.hidden.slice().sort((a, b) => a.why.localeCompare(b.why) || a.src.localeCompare(b.src))) {
  if (h.why !== why) { lines.push(`  // ${h.why}`); why = h.why; }
  lines.push(`  ${q(h.src)},`);
}
lines.push("]);\n");
lines.push("const crisp = new Set<string>([");
for (const s of data.crisp) lines.push(`  ${q(s)},`);
lines.push("]);\n");
lines.push("export const composites: ExtraComposite[] = [");
for (const c of data.composites) {
  lines.push("  {");
  lines.push(`    width: ${c.width},`);
  lines.push(`    height: ${c.height},`);
  lines.push("    tiles: [");
  for (const t of c.tiles) lines.push(`      { src: ${q(t.src)}, x: ${t.x}, y: ${t.y}, w: ${t.w}, h: ${t.h} },`);
  lines.push("    ],");
  if (c.fills.length) {
    lines.push("    fills: [");
    for (const f of c.fills) lines.push(`      { x: ${f.x}, y: ${f.y}, w: ${f.w}, h: ${f.h}, color: ${q(f.color)} },`);
    lines.push("    ],");
  } else lines.push("    fills: [],");
  lines.push(`    parts: [${c.parts.map(q).join(", ")}],`);
  lines.push("  },");
}
lines.push("];\n");
lines.push(`/** True when a picture is page furniture rather than a picture. */
export const isHiddenExtraImage = (src: string) => hidden.has(src);

/** True for a small graphic that is never drawn larger than its own pixels. */
export const isCrispExtraImage = (src: string) => crisp.has(src);
`);
fs.writeFileSync("src/data/extrasLayout.ts", lines.join("\n"));
console.log(`src/data/extrasLayout.ts: ${data.hidden.length} hidden, ${data.composites.length} composites, ${data.crisp.length} crisp`);
