// Generates object-position focal points for every story image, so cards that
// crop a photograph (square tiles, portrait plates, landscape strips) keep the
// subject in frame instead of cutting through a centred crop.
//
// Each axis is found with sharp's "attention" crop strategy (favours skin
// tones, saturated colour and luminance detail): the image is cropped along
// that axis only, and the crop offset becomes the object-position percentage
// for that axis, i.e. offset / (size - cropSize), which is exactly how CSS
// object-position places an image that overflows its box.
//
// Writes src/lib/imageFocus.auto.ts. Hand-tuned values in imageFocus.ts win.
// Usage (from .qa/): node image-focus.mjs [--sheet slug,slug,...]
import fs from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const sharp = require("../node_modules/sharp");

const ROOT = "../public";
const DIR = "images/stories";
const OUT = "../src/lib/imageFocus.auto.ts";
// Share of the image kept when probing an axis: the tighter crops cards use
const KEEP = 0.62;

async function walk(dir) {
  const out = [];
  for (const e of await fs.readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(p)));
    else if (/\.(webp|jpe?g|png)$/i.test(e.name)) out.push(p);
  }
  return out;
}

// Attention-crop offset along one axis, as a percentage of the free travel
async function axis(file, W, H, cw, ch, which) {
  const { info } = await sharp(file)
    .resize(cw, ch, { fit: "cover", position: sharp.strategy.attention })
    .toBuffer({ resolveWithObject: true });
  const offset = which === "x" ? -(info.cropOffsetLeft ?? 0) : -(info.cropOffsetTop ?? 0);
  const travel = which === "x" ? W - cw : H - ch;
  if (travel <= 0) return 50;
  return Math.max(0, Math.min(100, Math.round((Math.abs(offset) / travel) * 100)));
}

// Attention alone chases detail (hands, guitars, plates) and can crop a head
// off, so it only steers each axis halfway from centre
const steer = (v) => Math.round(50 + (v - 50) * 0.5);

// Where the subject starts on a cut-out photograph (plain background): rows
// above it that match the corner colour are trimmed. 0 when nothing trims.
async function contentTop(file) {
  try {
    const { info } = await sharp(file).trim({ threshold: 18 }).toBuffer({ resolveWithObject: true });
    return Math.abs(info.trimOffsetTop ?? 0);
  } catch {
    return 0;
  }
}

async function focus(file) {
  const { width: W, height: H } = await sharp(file).metadata();
  const side = Math.min(W, H);
  let x = 50;
  let y = 50;
  if (H > W * 1.05) {
    // Portrait: square tiles crop the height; narrow plates crop the width.
    // People are the usual subject and their heads sit high, so the crop never
    // starts lower than 30% of the travel, nor below the top of a cut-out.
    const travel = H - side;
    const top = await contentTop(file);
    const headroom = Math.round(H * 0.03);
    const cutout = top > 0 ? Math.max(0, Math.round(((top - headroom) / travel) * 100)) : 100;
    y = Math.min(await axis(file, W, H, W, side, "y"), 30, cutout);
    x = steer(await axis(file, W, H, Math.round(W * KEEP), H, "x"));
  } else if (W > H * 1.05) {
    // Landscape: square tiles crop the width; wide strips crop the height
    x = steer(await axis(file, W, H, side, H, "x"));
    y = Math.min(steer(await axis(file, W, H, W, Math.round(H * KEEP), "y")), 50);
  } else {
    x = steer(await axis(file, W, H, Math.round(W * KEEP), H, "x"));
    y = Math.min(steer(await axis(file, W, H, W, Math.round(H * KEEP), "y")), 40);
  }
  return { x, y, W, H };
}

const files = (await walk(path.join(ROOT, DIR))).sort();
const map = {};
let n = 0;
for (const f of files) {
  const key = "/" + path.relative(ROOT, f).split(path.sep).join("/");
  const { x, y } = await focus(f);
  map[key] = `${x}% ${y}%`;
  if (++n % 100 === 0) console.log(n, "/", files.length);
}

const body = Object.entries(map)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join("\n");
await fs.writeFile(
  OUT,
  `/*
 * Generated by .qa/image-focus.mjs — do not edit by hand.
 * Focal points (CSS object-position) for every story image, found with an
 * attention crop along each axis. Hand-tuned values in imageFocus.ts win.
 */
export const AUTO_FOCUS: Record<string, string> = {
${body}
};
`,
);
console.log("wrote", Object.keys(map).length, "focal points");

// Optional contact sheet: centred vs. focused square crops, side by side
const sheetArg = process.argv.find((a) => a.startsWith("--sheet="));
if (sheetArg) {
  const want = sheetArg.slice(8).split(",");
  const picks = Object.keys(map).filter((k) => want.some((w) => k.includes(w)));
  const T = 220;
  const tiles = [];
  for (const [i, k] of picks.entries()) {
    const f = path.join(ROOT, k);
    const { width: W, height: H } = await sharp(f).metadata();
    const s = Math.min(W, H);
    const [px, py] = map[k].split(" ").map((v) => parseFloat(v) / 100);
    const centre = await sharp(f).extract({ left: Math.round((W - s) / 2), top: Math.round((H - s) / 2), width: s, height: s }).resize(T, T).toBuffer();
    const focused = await sharp(f).extract({ left: Math.round((W - s) * px), top: Math.round((H - s) * py), width: s, height: s }).resize(T, T).toBuffer();
    tiles.push({ input: centre, left: 0, top: i * (T + 8) }, { input: focused, left: T + 8, top: i * (T + 8) });
  }
  await sharp({ create: { width: 2 * T + 8, height: picks.length * (T + 8), channels: 3, background: "#fff" } })
    .composite(tiles)
    .png()
    .toFile("screenshots/image-focus-sheet.png");
  console.log("sheet:", picks.join(", "));
}
